version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php-nginx/Dockerfile
    container_name: symfony_app
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://myuser:mypassword@db:3306/mydb"
    volumes:
      - .:/var/www/symfony
    # Add healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  db:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    # Add healthcheck
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -ppassword | grep 'mysqld is alive' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
