version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php-nginx/Dockerfile
    container_name: symfony_app
    ports:
      - "8080:80" # Access your Symfony app at http://localhost:8080
    depends_on:
      - db
    environment:
      # Symfony will use this to connect to the database
      DATABASE_URL: "mysql://myuser:mypassword@db:3306/mydb"
    volumes:
      # Bind-mount your project so changes are reflected in the container in real time
      - .:/var/www/symfony

  db:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306" # Optional. Access MySQL on localhost:3307
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
